# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 23:55
from __future__ import unicode_literals

import BeginningDash.formatChecker
import BeginningDash.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_group', models.CharField(max_length=100)),
                ('comment', models.CharField(default='', max_length=1000)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('VIDEO', BeginningDash.formatChecker.ContentTypeRestrictedFileField(blank=True, db_index=True, null=True, upload_to='uploads')),
                ('AUDIO', BeginningDash.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads')),
                ('PDF', BeginningDash.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads')),
                ('IMAGE', BeginningDash.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MemberUpload',
                'verbose_name_plural': 'MemberUploads',
                'ordering': ('-date_uploaded',),
            },
        ),
        migrations.CreateModel(
            name='NewsByAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Heading', models.CharField(max_length=50)),
                ('News', models.CharField(default='', max_length=10000)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('importance', models.CharField(choices=[('Free Users', 'Free Users.'), ('Premium Users', 'Premium Users'), ('Both Free And Premium Users', 'Both Free And Premium Users')], max_length=50)),
            ],
            options={
                'verbose_name': 'NewsByAdmin',
                'verbose_name_plural': 'NewsByAdmins',
                'ordering': ['-time', '-date'],
            },
        ),
        migrations.CreateModel(
            name='say_something_nice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Comment', models.TextField(max_length=200)),
                ('Occupation', models.CharField(max_length=50)),
                ('Photo', models.ImageField(height_field='userheight_field', help_text='** Reviews With Uploaded Face-Images are Usually Displayed **', upload_to=BeginningDash.models.upload_location_Site_Evaluator_image, width_field='userwidth_field')),
                ('userheight_field', models.IntegerField(default=100)),
                ('userwidth_field', models.IntegerField(default=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('show', 'Show'), ('hide', 'Hide')], default='hide', max_length=34)),
            ],
            options={
                'verbose_name': 'say_something_nice',
                'verbose_name_plural': 'say_something_nice',
                'ordering': ('-created',),
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UMCU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=100)),
                ('says', models.CharField(default='', max_length=1000)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('HTML', BeginningDash.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads')),
                ('CSS', BeginningDash.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MemberCodeUpload',
                'verbose_name_plural': 'MemberCodeUploads',
                'ordering': ('-uploaded_time',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
