# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BeginningDash', '0002_auto_20180802_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactXModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(default='', max_length=1000)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ContactForm',
                'verbose_name_plural': 'ContactForm',
                'ordering': ('-sent_time',),
            },
        ),
    ]
